<?php

namespace App\Filament\Movelveiculos\Resources\Entregas\Pages;

use App\Filament\Movelveiculos\Resources\Entregas\EntregaResource;
use App\Models\Empresa;
use Filament\Actions\Action;
use Filament\Resources\Pages\CreateRecord;
use Filament\Support\Enums\Size;
use Illuminate\Support\Facades\Storage;

class CreateEntrega extends CreateRecord
{
    protected static string $resource = EntregaResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['empresa_id'] = Empresa::MOVEL_VEICULOS_ID;
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
