<?php

namespace App\Filament\Movelveiculos\Resources\SolicitacaoDeEntregas\Pages;

use App\Filament\Movelveiculos\Resources\SolicitacaoDeEntregas\SolicitacaoDeEntregaResource;
use App\Models\Empresa;
use Filament\Resources\Pages\CreateRecord;

class CreateSolicitacaoDeEntrega extends CreateRecord
{
    protected static string $resource = SolicitacaoDeEntregaResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['empresa_id'] = Empresa::MOVEL_VEICULOS_ID;
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
