<?php

namespace App\Filament\Bydconquista\Resources\Entregas\Pages;

use App\Filament\Bydconquista\Resources\Entregas\EntregaResource;
use App\Models\Empresa;
use Filament\Resources\Pages\CreateRecord;

class CreateEntrega extends CreateRecord
{
    protected static string $resource = EntregaResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['empresa_id'] = Empresa::BYD_CONQUISTA_ID;
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
